### ISSUE TITLE
colQuantiles and rowQuantiles discrepancy with matrixStats in all-NA case

### ISSUE THREAD

**Issue by LTLA** [const-ae/sparseMatrixStats#11]
Consider the following:

```r
library(Matrix)
mat <- matrix(NA, 10, 10)
smat <- as(mat, "lgCMatrix")

library(MatrixGenerics)
typeof(colQuantiles(smat))
## [1] double
```

Technically, this is not an error of SMS, which does the right thing by returning a numeric matrix. ("Right" being defined in terms of what `?matrixStats::colQuantiles` says it should do, which is to return a numeric matrix.) However, it does cause a discrepancy with **matrixStats**, which does the wrong thing by returning a logical matrix:

```r
typeof(matrixStats::colQuantiles(mat))
## [1] "logical"
```

I believe the same issue affects `colWeightedVar` and `rowWeightedVar`, though I haven't looked too closely at that.

In the short term, I have disabled the relevant tests in DMS to get everything to work. But one way or another, we should get consistency with the **matrixStats** output, whether you change SMS to mimic the MS output or request a fix to MS itself.

**Comment by const-ae** [comment]
Henrik merged the fix for this issue.

``` r
suppressPackageStartupMessages({
  library(sparseMatrixStats)
})
mat <- matrix(NA, 10, 10)
smat <- as(mat, "lgCMatrix")
typeof(colQuantiles(smat))
#> [1] "double"
typeof(matrixStats::colQuantiles(mat))
#> [1] "double"
```

<sup>Created on 2020-12-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
