### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by vjbaskar** [const-ae/sparseMatrixStats#14]
Hi I am trying to install sparseMatrixStats and it fails with the following error

`
g++ -Wno-unused-function  -I"/rds/project/bg200/rds-bg200-hphi-gottgens/users/vs401/soft/__R/lib64/R/include" -DNDEBUG  -I'/rds/project/bg200/rds-bg200-hphi-gottgens/users/vs401/soft/__R/lib64/R/library/Rcpp/include' -I/usr/local/include      -c SparseMatrixView.cpp -o SparseMatrixView.o

In file included from SparseMatrixView.cpp:3:0:
VectorSubsetView.h:32:11: error: expected nested-name-specifier before ‘iterator_category’
     using iterator_category = std::forward_iterator_tag;
           ^
VectorSubsetView.h:32:11: error: using-declaration for non-member at class scope
VectorSubsetView.h:32:29: error: expected ‘;’ before ‘=’ token
     using iterator_category = std::forward_iterator_tag;
                             ^

VectorSubsetView.h:32:29: error: expected unqualified-id before ‘=’ token
VectorSubsetView.h:33:11: error: expected nested-name-specifier before ‘value_type’
     using value_type = stored_type;

`
My R version is 4.0.3 and g++ version is (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by const-ae** [comment]
Hi Vijay,

I am pretty sure the error comes from the fact that your compiler is too old. `sparseMatrixStat` uses some C++14 features which GCC 4.8 does not support. For an overview which features are available in which GCC version see https://gcc.gnu.org/projects/cxx-status.html

I am actually not 100% sure, which is the minimum version of GCC to compile `sparseMatrixStat`, but I think GCC 5 at least would be good.

Best,
Constantin

**Comment by HenrikBengtsson** [comment]
@const-ae, RedHat/CentOS 7 comes with only gcc 4.8.5.  Lots of people in academia are on RHEL/CentOS clusters and several of them won't be updated to version 8 until long-term support for version 7 is dropped.  

Many people are not aware of compiler versions, how they relate to C++14 (and knowing that you've documented the latter req in DESCRIPTION).   Because of this, I think there will be lots of people that will struggle with this.  It's a recurring problem among users on the clusters I've been on.

I think it would be helpful to identify the lowest version of gcc that this package supports, or at least the versions that are _not_ supported.  With this, I think it's possible(*) to set up a configure script that could assert that the available gcc version is sufficient or not.   (*) I don't know how to do this, but I've seen lots of examples where the config step fails due to old compiler versions.  If this could be implemented, I think you'll spare others and yourself lots of time on this.

**Comment by HenrikBengtsson** [comment]
@vjbaskar, if your RedHat cluster has Software Collections (SCLs) installed, which it probably has, you can install the packages by launching R as:

```r
$ scl enable devtoolset-8 R
```

This will give you access to:

```r
> system("gcc --version")
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

throughout the R session.  This means you can _install_ **sparseMatrixStats**.    It's only needed for the installation, so you don't have to enable the SCL when you use the package later.

See also: https://wynton.ucsf.edu/hpc/software/scl.html

**Comment by vjbaskar** [comment]
@HenrikBengtsson Thanks. Our HPC runs on Scientific Linux 7.9 (so RedHat) and scl seem to not have anything listed in it. There is devtoolset-3 which I am assuming is too old. 

I would love to help with finding out the least gcc version need for the package but I do not have necessary permissions to play around with versions. 
But I can tell you that the package does not compile with gcc=4.8.5 but compiled fine with gcc=5.4.0. Hope this is of some help to the community!

**Comment by const-ae** [comment]
> > But I can tell you that the package does not compile with gcc=4.8.5 but compiled fine with gcc=5.4.0. Hope this is of some help to the community!

Thanks @vjbaskar, this will already be helpful in the future :)

> I think it would be helpful to identify the lowest version of gcc that this package supports, or at least the versions that are not supported. With this, I think it's possible() to set up a configure script that could assert that the available gcc version is sufficient or not. () I don't know how to do this, but I've seen lots of examples where the config step fails due to old compiler versions. If this could be implemented, I think you'll spare others and yourself lots of time on this.

Yes, I agree. I yesterday tried to adapt the R-base docker container to install older gcc versions, but it kept failing. Is there any other simple method to try multiple different gcc versions and test the compilation, without debugging the best Debian gcc version combination and then struggle to install R?

**Comment by const-ae** [comment]
> Is there any other simple method to try multiple different gcc versions and test the compilation, without debugging the best Debian gcc version combination and then struggle to install R?

To answer my own question: No. But having gone through all this trouble now, I have learned quite a bit.

I have added a new section to the README that describes how to fix problems with the installation https://github.com/const-ae/sparseMatrixStats#installation-problems

I also was able to verify that `gcc` version 4.9 is able to install `sparseMatrixStats`, but only if you provide the necessary Makevars variables. For example you can say:

```
withr::with_makevars(
 new = c(CXX14 = "g++", CXX14FLAGS = "-g -O2 $(LTO)", 
         CXX14PICFLAGS = "-fpic", CXX14STD = "-std=gnu++14"), 
 code = {
   BiocManager::install("sparseMatrixStats")
 })
```


-------

If I understood @vjbaskar correctly, they were able to install `sparseMatrixStats` using gcc-5.4, so I will close this issue. If I misunderstood something, feel free to reopen.
