### ISSUE TITLE
Test fail on arm64 and armhf systems

### ISSUE THREAD

**Issue by mr-c** [const-ae/sparseMatrixStats#16]
Hello,

Volunteers with the Debian project have recently packaged sparseMatrixStats as `r-bioc-sparsematrixstats` for Debian. While running the included tests, we noticed they fail on some architectures, specifically [arm64](https://wiki.debian.org/Arm64Port) and [armhf](https://wiki.debian.org/ArmHardFloatPort).

The tests did pass on amd64, i386, and ppc64el

Full logs:

https://ci.debian.net/data/autopkgtest/testing/arm64/r/r-bioc-sparsematrixstats/7988852/log.gz

https://ci.debian.net/data/autopkgtest/testing/armhf/r/r-bioc-sparsematrixstats/7989020/log.gz

Example failure
```
> test_check("sparseMatrixStats")
── 1. Failure: colCounts works (@test-functions.R#140)  ────────────────────────
colCounts(sp_mat, value = 0) not equal to matrixStats::colCounts(mat, value = 0).
2/10 mismatches (average diff: NaN)
[3] 0 - NA == NA
[4] 0 - NA == NA
```

Any patches to fix this (or a new release) would be greatly appreciated!

Many thanks for contributing scientific open source software.

**Comment by const-ae** [comment]
Hi,

thanks for the report. This is quite helpful as I don't have direct access to an ARM machine to test those myself. However, I am currently planing with a colleague (@grimbough) to maybe repurpose a Raspberry Pi, so that we can test on ARM, which I guess will become more important in the future with the new MacBook.

Concerning the issue that you report, I wonder if it is related to the fast-mode mentioned in the blog post on [running R on ARM](https://developer.r-project.org/Blog/public/2020/11/02/will-r-work-on-apple-silicon/index.html).

Without a proper setup to reproduce the issue, I am afraid I cannot do much to fix the issue.

Best, Constantin

**Comment by mr-c** [comment]
You are welcome @const-ae,

Besides the Raspberrry PI, you can test using emulation:

If you have access to a Debian machine, then you can test using qemu

I can also put together a Dockerfile that builds sparseMatrixStats using qemu

There are general pointers at https://github.com/simd-everywhere/simde/wiki/Development-Environment#arm but it is probably easier for me to put together a Dockefile for you.

**Comment by const-ae** [comment]
> I can also put together a Dockerfile that builds sparseMatrixStats using qemu

Sorry, I am quite naive about this topic. I am using a MacBook, but have Docker installed. Would I be able to test the Docker image with that setup? I also have access to a CentOS 7 cluster, but I am not sure if I can get Docker to work there.

**Comment by mr-c** [comment]
>  I am using a MacBook, but have Docker installed. Would I be able to test the Docker image with that setup?

You will, yep! Docker on Mac uses a Linux virtual machine. I'll reply again with the recipe

**Comment by HenrikBengtsson** [comment]
Unless I have misunderstood it all, I think Travis CI test on "AMD64", cf. https://travis-ci.org/github/HenrikBengtsson/matrixStats.  So, it seems like setting Travis CI would be the simplest thing here.

**Comment by const-ae** [comment]
As I am currently using GitHub Actions for testing, I would like to avoid transitioning to Travis. In particular, since I recently read they seem to be planning to shut down the free tier(?!).

**Comment by mr-c** [comment]
R packages are harder to cross-build than I expected, and I'm having difficulties with qemu inside docker. We can send in an application for you to get an account on https://db.debian.org/machines.cgi?host=amdahl if you can send me the data under  "Information guest needs to supply to sponsoring DD" at https://dsa.debian.org/doc/guest-account/

**Comment by const-ae** [comment]
Hm, that does seem a bit more complicated than I expected. I think, the more sustainable way forward will to wait until we have installed a Raspberry at our institute, so that I can continuously test new developments on an ARM machine. 

@mr-c, thank you again for all the effort :)

**Comment by HenrikBengtsson** [comment]
You can run both GA and Travis. You can run them conditionally on a branch, commit message, ... to only run it occasionally. Adding Travis takes < 15 min and you're done

**Comment by mr-c** [comment]
@const-ae Does the command ` docker run --rm --privileged fkrull/qemu-user-static enable` exit successfully on your mac?

**Comment by mr-c** [comment]
Here's a recipe:


Run `docker run --rm --privileged fkrull/qemu-user-static enable`

And then, from within a checkout of the `sparseMatrixStats` source code make the following file
> Dockerfile.arm32v7
```
FROM docker.io/arm32v7/debian:unstable-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && apt-get install -y --no-install-recommends \
        r-base-core r-base-dev r-cran-rcmdcheck r-cran-knitr r-bioc-matrixgenerics \
        r-cran-rcpp r-cran-matrix r-cran-matrixstats r-cran-rmarkdown \
        pandoc-citeproc r-bioc-biocstyle r-cran-testthat

COPY . /build
WORKDIR /build
RUN R CMD INSTALL .
```

And then build the Docker container

```
docker build -t sparseMatrixStats_arm32v7 -f Dockerfile.arm32v7 .
```
And then log into it and run the tests
```
docker run -it sparseMatrixStats_arm32v7 /bin/bash
root@03ff177c6d7a:/build# cd tests/
root@03ff177c6d7a:/build/tests# R --no-save < testthat.R 
# some tests fail, debug as normal inside the container
```

Same procedure for arm64 testing:
> Dockerfile.arm64v8
```
FROM docker.io/arm64v8/debian:unstable-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update && apt-get install -y --no-install-recommends \
        r-base-core r-base-dev r-cran-rcmdcheck r-cran-knitr r-bioc-matrixgenerics \
        r-cran-rcpp r-cran-matrix r-cran-matrixstats r-cran-rmarkdown \
        pandoc-citeproc r-bioc-biocstyle r-cran-testthat

COPY . /build
WORKDIR /build
RUN R CMD INSTALL .
```
`docker build -t sparseMatrixStats_arm64v8 -f Dockerfile.arm64v8 .`

**Comment by mr-c** [comment]
@const-ae According to https://twitter.com/milot_mirdita/status/1332001985126600707 you might not need the `docker run --rm --privileged fkrull/qemu-user-static enable` line, so feel free to first try without it.

**Comment by const-ae** [comment]
I did already call `docker run --rm --privileged fkrull/qemu-user-static enable`. I also already build the Dockerfile.arm32v7 container. 

There were a few scary warnings when it build but it finished successfully and I can reproduce your initial report with the `NA` vs `0` mismatch. I will try to debug this in the coming days.

@mr-c, thank you so much for your help :)

**Comment by grimbough** [comment]
@const-ae  I also now have a GitHub Actions workflow for testing packages using QEMU at https://github.com/grimbough/rhdf5filters/blob/master/.github/workflows/multi-arch.yml

It's a little convoluted, and won't create vignettes as there's no pandoc as it stands, but it should build the package and run all tests, examples, and vignette code on arm64.  I was able to recreate the error reported by @mr-c in https://github.com/grimbough/rhdf5filters/issues/3

I don't think there's anything package specific in there; hopefully you can just drop it fairly easily into your repository if looks helpful.

**Comment by const-ae** [comment]
I finally managed to fix the issue.

The problem is that I internally relied on the fact that the conversion of `NA_REAL` to `int` gives `NA_INTEGER`, but this is not true on ARM.

When I run the following locally:

```
Rcpp::cppFunction(r"(
void casting_nas(){
  Rcpp::Rcout << "NA_REAL (" << NA_REAL << ") cast to int: " << ((int) NA_REAL) << 
     " which is equal to NA_INTEGER: " <<  (((int) NA_REAL) == NA_INTEGER) << "\n";
}        
)")
```

I get 
```
NA_REAL (nan) cast to int: -2147483648 which is equal to NA_INTEGER: 1
```
However, in the Docker container provided by @mr-c, I get 
```
NA_REAL (nan) cast to int: 0 which is equal to NA_INTEGER: 0
```


Thanks again to everyone involved and in particular to @mr-c, for taking the time to help me with Docker and fix this bug :)

**Comment by mr-c** [comment]
Adding https://github.com/const-ae/sparseMatrixStats/commit/83a1cf12b70511533cb7f2a45f07f4be97fb8503 & https://github.com/const-ae/sparseMatrixStats/commit/b4e453229126f475481793f8e3d095d7b297a68a to 1.2.0 release fixes the tests on all the official Debian architectures, thanks!

**Comment by const-ae** [comment]
Perfect, thanks for reporting and bearing with me :)
