### ISSUE TITLE
Linux Build Error

### ISSUE THREAD

**Issue by errcricket** [const-ae/sparseMatrixStats#17]
I am getting the same error listed [here](https://github.com/const-ae/sparseMatrixStats/issues/2), but I am using Linux.

Here is my system information: 
```
Bioconductor version 3.12 (BiocManager 1.30.10)
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

Here is my installation command: 
```
BiocManager::install("sparseMatrixStats")
```

Here is the error:
```
* installing *source* package ‘sparseMatrixStats’ ...
** using staged installation
** libs
Error: C++14 standard requested but CXX14 is not defined
```

I did see in the referenced issue that directions are to be included in the README, but I did not find it. And if I did, I am not sure how it is applicable since I am not using Windows. How can I fix this?

**Comment by const-ae** [comment]
Hi Noire,

I have just added a new section to the README that describes how to fix problems with the installation https://github.com/const-ae/sparseMatrixStats#installation-problems

Could you check if this fixes your problem and if not, provide the necessary details for me to debug the problem.

Best,
Constantin

**Comment by errcricket** [comment]
Constantin,

Yes!!! This is what made it into the final Makevars file.

```  
CXX14FLAGS=-fPIC
CXX14=g++
```

Thank you.

**Comment by const-ae** [comment]
Happy to hear that you solved the problem 🎉
