### ISSUE TITLE
Missing lgCMatrix support

### ISSUE THREAD

**Issue by frederikziebell** [const-ae/sparseMatrixStats#6]
Hi Constantin,

are you planning on adding support for the lgCMatrix class? E.g.

```
set.seed(1)
mat <- Matrix::Matrix(rpois(10^2,.3),ncol=10) > 0
sparseMatrixStats::colSums2(mat)
```

Since matrixStats is supporting logical matrices, I think it makes sense to have this feature available.

Best,
Frederik

**Comment by const-ae** [comment]
Fully agree. Checkout the master branch:

``` r
set.seed(1)
mat <- Matrix::Matrix(rpois(10^2,.3),ncol=10) > 0
sparseMatrixStats::colSums2(mat)
#>  [1] 3 3 2 2 3 1 3 5 1 4
```

<sup>Created on 2020-09-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
