### ISSUE TITLE
colWeightedMads does not preserve the column names

### ISSUE THREAD

**Issue by LTLA** [const-ae/sparseMatrixStats#9]
```r
library(Matrix)
x <- rsparsematrix(10, 10, density=0.5)
colnames(x) <- LETTERS[1:10]

library(sparseMatrixStats)
colWeightedMads(x)
##  [1] 0.0000000 0.1630860 0.2001510 0.0000000 0.0926625 0.3854760 0.0526323
##  [8] 0.0000000 0.0815430 0.0000000

library(matrixStats)
matrixStats::colWeightedMads(as.matrix(x))
##         A         B         C         D         E         F         G         H 
## 0.0000000 0.1630860 0.2001510 0.0000000 0.0926625 0.3854760 0.0526323 0.0000000 
##         I         J 
## 0.0815430 0.0000000 
```

The opposite applies for `colWeightedMedians`, where column names are returned when they shouldn't be.

Arguably, the inclusion of column names in `colWeightedMads` seems like a **matrixStats** oversight, but until/unless it is fixed, SMS should try to mimic the output format as closely as possible.

**Comment by const-ae** [comment]
Hi Aaron, 

thanks for the report. I fully agree that `sparseMatrixStats` should mimic `matrixStats` as closely as possible.  Accordingly, I also adapted `colWeightedMedians` as well.

**Comment by const-ae** [comment]
https://github.com/HenrikBengtsson/matrixStats/issues/175 contains some more context for Henrik's thinking on naming the output of `matrixStats`
